### ISSUE TITLE
Extra elements as optional information

### ISSUE THREAD

**Issue by karinoolu** [DILCISBoard/GroupDocumentation#11]
In Sweden we have not created separate FGSs for SIP, AIP and DIP. We recommend that all extra elements for SIP, AIP and DIP should be included in CSIP, but as optional information. Then, documents are needed that describe how to create a SIP, AIP, DIP and how to use the elements at EU level and that it is possible to adapt for local use in different countries.

**Comment by karinbredenberg** [comment]
Decision has been made to keep the specifications as they are and not at this stage merge them.
