### ISSUE TITLE
Common structure

### ISSUE THREAD

**Issue by karinoolu** [DILCISBoard/GroupDocumentation#12]
The documents for the different IPs should be standardized so that they are structured in a similar way and the references should keep the same ID for the same element (CSIP7 should always be the same element in all documents).

**Comment by karinbredenberg** [comment]
Investigate possibility and how to do it to connect requirements between the different specifications.

**Comment by jmaferreira** [comment]
Points of standardisation between specs:

- [ ] List of authors and reviewers (at least the way this information is presented)
- [ ] History of the specification
- [ ] Spec map or guide through the entire set of specifications
- [ ] Overall design including cover and images
- [ ] Section names and order

**Comment by karinbredenberg** [comment]
The documents will have similar structure but not all parts will be the same depending on which specification it is.
It is not possible to keep the requirement numbers between the specifications, they will remain as they are.
