### ISSUE TITLE
Review of the E-ARK CS from 2016 

### ISSUE THREAD

**Issue by karinoolu** [DILCISBoard/GroupDocumentation#13]
In 2016 the Digital Archiving Expert Group of eCH, the Swiss organisation for e-government standardisation, set out to work on a revised SIP specification, with the aim of replacing the existant eCH-0160 SIP specification in the middle and long terms. Part of our early work was a thorough review of the then freshly published E-ARK specifications, in particular the Common Specification. We later abandoned the idea of building on the E-ARK specifications and took another path. We believe that our 2016 analysis, albeit probably outdated, might prove valuable to the DILCIS board. The following is a summary of our findings, pulled together from various minutes and other documents. Please note that we have not updated our analysis and submit it in the state of 2016.

**Comment by karinbredenberg** [comment]
This relates to version 2016.

**Comment by karinbredenberg** [comment]
Connected to CSIP issues:
CSIP issue 356 [https://github.com/DILCISBoard/E-ARK-CSIP/issues/356](https://github.com/DILCISBoard/E-ARK-CSIP/issues/356)
CSIP issue 357 [https://github.com/DILCISBoard/E-ARK-CSIP/issues/357](https://github.com/DILCISBoard/E-ARK-CSIP/issues/357)
CSIP issue 358 [https://github.com/DILCISBoard/E-ARK-CSIP/issues/358](https://github.com/DILCISBoard/E-ARK-CSIP/issues/358)
CSIP issue 359 [https://github.com/DILCISBoard/E-ARK-CSIP/issues/359](https://github.com/DILCISBoard/E-ARK-CSIP/issues/359)
CSIP issue 360 [https://github.com/DILCISBoard/E-ARK-CSIP/issues/360](https://github.com/DILCISBoard/E-ARK-CSIP/issues/360)
