### ISSUE TITLE
Should we refer to the common spec as "CSIP" or "CS IP"?

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/GroupDocumentation#16]
There are various occurrences of "CSIP" on the METS profiles, however, on the texts we tend to use "CS IP". 

Please clarify.

**Comment by karinbredenberg** [comment]
We made a decision in December to use CSIP. Fixing is ongoing.

**Comment by jmaferreira** [comment]
Sorry to come back to this, but are you sure that was the decision?!
To me it seems more confusing to use CSIP.

**Comment by PhillipTommerholt** [comment]
I also thought we agreed on using CS IP :)

**Comment by PhillipTommerholt** [comment]
We discussed it here: https://github.com/DILCISBoard/E-ARK-CSIP/issues/229 (and also at a meeting?)

**Comment by carlwilson** [comment]
CSIP consistently used now following https://github.com/DILCISBoard/E-ARK-CSIP/pull/424
