### ISSUE TITLE
There is an image missing on the website

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/GroupDocumentation#2]
![screen shot 2018-09-05 at 10 48 48](https://user-images.githubusercontent.com/3181302/45085750-5b4e3f00-b0f9-11e8-8b30-0bcdf65b07e0.png)

**Comment by PhillipTommerholt** [comment]
I don't see this in Chrome or Firefox..

**Comment by jmaferreira** [comment]
That right. There is an image there (NOT FOUND) and chrome doesn't render it. Safari creates a placeholder for it.

More info on the file bellow:

<img width="1753" alt="screen shot 2018-09-05 at 10 55 46" src="https://user-images.githubusercontent.com/3181302/45086107-576eec80-b0fa-11e8-8e36-28d83bd80c63.png">

**Comment by kuldaraas** [comment]
Yes, I'm usually working in Chrome and didn't see it even in the Joomla WYSIWYG editor, apologies! Cleaned the code and tested with Edge, should be fine now - you're welcome to confirm with Safari/Firefox as well!
