### ISSUE TITLE
We should update the email address of the DILCIS board (its still linked to DASBOARD)

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/GroupDocumentation#3]
![screen shot 2018-09-05 at 10 51 13](https://user-images.githubusercontent.com/3181302/45085869-aa946f80-b0f9-11e8-9fde-4039cfe3a771.png)

**Comment by kuldaraas** [comment]
Once new e-mail addresses are set up (within the dilcis.eu domain?) I'm happy to change the website! I think David is the "owner" of the domain --> hope @karinbredenberg can take this issue to him?

**Comment by karinbredenberg** [comment]
I'm making some research!

**Comment by karinbredenberg** [comment]
we have the e-mail: info@dilcis.eu to use now.

**Comment by kuldaraas** [comment]
E-mail address has been updated throughout the website.
