### ISSUE TITLE
Quality of figures

### ISSUE THREAD

**Issue by karinoolu** [DILCISBoard/GroupDocumentation#5]
Quality of figure is very poor in most of the figures, that is, the text in a figure is unreadable.

**Comment by karinbredenberg** [comment]
All images is updated.

**Comment by PhillipTommerholt** [comment]
@karinbredenberg 

Are the updated images available at the current http://earkcsip.dilcis.eu/ ?
The image under "Principle 3.6" seems to be unreadable.

**Comment by DrJaime** [comment]
Hi Phillip,

The images are in the A2 folder in the G drive. There are various
subfolders for CSIP, SIP, AIP, and DIP.

Karin needs to give then the final sign off then they can be integrated.

Best wishes,


Jaime

**Comment by PhillipTommerholt** [comment]
Thanks for the clarification @DrJaime :+1:
