### ISSUE TITLE
More dense standard

### ISSUE THREAD

**Issue by karinoolu** [DILCISBoard/GroupDocumentation#9]
A general comment is that the standard could me more “dense”, meaning that less of the rationale for creating a standard and arguments for why the standard exists can be moved to a separate document or appendix. From a developer point of view a more dense standard makes it easier to read and implement correctly.

**Comment by karinbredenberg** [comment]
Possible to create short lists of all requirements? And describe where to find it, appendix, own document?

**Comment by karinbredenberg** [comment]
Appendix with just the requirements is available. Guidelines will be created which can make move of text not making changes to the requirements in CSIP occurs.
